blank_issues_enabled: false
contact_links:
  - name: DivineMC Discord
    url: https://discord.gg/PrKTKfR579
    about: If you are having issues, come ask us on our Discord server!
  - name: DivineMC Docs
    url: https://docs.bx-team.space/divinemc
    about: You can find some info at our docs
