blank_issues_enabled: false
contact_links:
  - name: BX Team Discord
    url: https://discord.gg/qNyybSSPm5
    about: If you are having issues, come ask us on our Discord server!
  - name: DivineMC Docs
    url: https://bxteam.org/docs/divinemc
    about: You can find some info at our docs
