name: Build Pull Request

on:
  pull_request:
    branches: [ "ver/1.21.7" ]

jobs:
  build:
    runs-on: blacksmith-8vcpu-ubuntu-2204
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: useblacksmith/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Configure Git and Gradle
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          chmod +x gradlew

      - name: Apply Patches
        run: ./gradlew applyAllPatches --stacktrace --no-daemon

      - name: Build Shuttle Jar
        run: ./gradlew createMojmapShuttleJar --stacktrace --no-daemon

      - name: Upload Artifacts
        uses: actions/upload-artifact@main
        with:
          name: DivineMC
          path: divinemc-server/build/libs/divinemc-shuttle-*-mojmap.jar
