name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Configure Git
        run: |
          git config --global user.email "no-reply@github.com"
          git config --global user.name "Github Actions"
          chmod +x gradlew
      - name: Patch
        run: |
          ./gradlew applyPatches --stacktrace
      - name: Build
        run: |
          ./gradlew createReobfPaperclipJar --stacktrace
      - name: Archive Paperclip
        uses: actions/upload-artifact@v3.1.0
        with:
          name: DivineMC-1.19.2
          path: build/libs/DivineMC-paperclip-1.19.2-R0.1-SNAPSHOT-reobf.jar