name: DivineMC CI

on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - name: Setup Action
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Setup JDK 22
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 22
          cache: 'gradle'

      - name: Configure Git and Gradle
        run: |
          git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
          echo "BUILD_NUMBER=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
          chmod +x gradlew

      - name: Patch
        run: ./gradlew applyAllPatches --stacktrace

      - name: Build Paperclip Jar
        run: ./gradlew createMojmapPaperclipJar --stacktrace

      - name: Publish API
        continue-on-error: true
        run: ./gradlew publish -PdivinemcUsername=${{ secrets.REPO_USERNAME }} -PdivinemcPassword=${{ secrets.REPO_SECRET }}

      - name: Get Release Info
        run: bash scripts/releaseInfo.sh
        env:
          BUILD_NUMBER: ${{ env.BUILD_NUMBER }}

      - name: Create Release
        uses: ncipollo/release-action@v1.15.0
        with:
          artifacts: ${{ env.jar }}
          bodyFile: ${{ env.info }}
          tag: ${{ env.tag }}
          name: ${{ env.name }}
          prerelease: ${{ env.experimental }}
          token: ${{ secrets.GITHUB_TOKEN }}
          makeLatest: ${{ env.make_latest }}
