name: DivineMC Test Build

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: blacksmith-8vcpu-ubuntu-2204
    steps:
      - name: Setup Action
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'gradle'

      - name: Configure Git and Gradle
        run: |
          git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
          chmod +x gradlew

      - name: Patch
        run: ./gradlew applyAllPatches --stacktrace

      - name: Build Paperclip Jar
        run: ./gradlew createMojmapPaperclipJar --stacktrace

      - name: Upload Artifacts
        uses: actions/upload-artifact@main
        with:
          name: DivineMC
          path: divinemc-server/build/libs/divinemc-paperclip-*-mojmap.jar
